In [2]:
import pandas as pd

In [3]:
#DICCIONARIO
data = {
    "Nombre" : ["Juan", "Luis", "Ana", "Maria"],
    "Edad" : [22,25,23,30],
    "Ciudad" : ["MAchala", "Quito", "Cuenca", "Guayaquil"]
}

data, type(data)

({'Nombre': ['Juan', 'Luis', 'Ana', 'Maria'],
  'Edad': [22, 25, 23, 30],
  'Ciudad': ['MAchala', 'Quito', 'Cuenca', 'Guayaquil']},
 dict)

In [4]:
#GENERAMOS UN DATAFRAME A PARTIR DEL DICCIONARIO

df = pd.DataFrame(data=data)
df

  Nombre  Edad     Ciudad
0   Juan    22    MAchala
1   Luis    25      Quito
2    Ana    23     Cuenca
3  Maria    30  Guayaquil

In [5]:
#SELECCIONAMOS UNA COLUMNA
nombres = df["Nombre"]
print(nombres, type(nombres))

0     Juan
1     Luis
2      Ana
3    Maria
Name: Nombre, dtype: str <class 'pandas.Series'>

In [6]:
#SELECCIONAMOS MAS DE UNA COLUMNA
df[["Nombre", "Ciudad"]]

  Nombre     Ciudad
0   Juan    MAchala
1   Luis      Quito
2    Ana     Cuenca
3  Maria  Guayaquil

In [7]:
#FILTRAR POR INIDCE
fila = df.loc[2]
print(fila)

Nombre       Ana
Edad          23
Ciudad    Cuenca
Name: 2, dtype: object

In [8]:
#FILTRAR POR CONDICION
df[df["Edad"] > 23]

  Nombre  Edad     Ciudad
1   Luis    25      Quito
3  Maria    30  Guayaquil

In [9]:
#DOBLE CONDICION
#df[(df["Edad"] > 23) & (df["Nombre"].str.startswith("M"))]
filtro = (df["Edad"] > 23) & (df["Nombre"].str.startswith("M"))
df[filtro]

  Nombre  Edad     Ciudad
3  Maria    30  Guayaquil

In [10]:
#filtrar por query
df.query("Edad > 23 and Nombre.str.startswith('M')")

  Nombre  Edad     Ciudad
3  Maria    30  Guayaquil

In [11]:
df[df["Nombre"].isin(["Luis", "Ana", "Carlos"])]

  Nombre  Edad  Ciudad
1   Luis    25   Quito
2    Ana    23  Cuenca

In [ ]:
# EXPORTAR UN DATADRAME A CSV
df.to_csv("datos.csv")

In [ ]:
#IMPORTAR UN CSV A UN DATAFRAME
#index_col=0 para que la primera columna se convierta en el indice del dataframe
import_df = pd.read_csv("datos.csv", index_col=0)
import_df

  Nombre  Edad     Ciudad
0   Juan    22    MAchala
1   Luis    25      Quito
2    Ana    23     Cuenca
3  Maria    30  Guayaquil