In [1]:
import pandas as pd

In [2]:
#DICCIONARIO
data = {
    "Nombre" : ["Juan", "Luis", "Ana", "Maria"],
    "Edad" : [22,25,23,30],
    "Ciudad" : ["MAchala", "Quito", "Cuenca", "Guayaquil"]
}

data, type(data)

({'Nombre': ['Juan', 'Luis', 'Ana', 'Maria'],
  'Edad': [22, 25, 23, 30],
  'Ciudad': ['MAchala', 'Quito', 'Cuenca', 'Guayaquil']},
 dict)

In [3]:
#GENERAMOS UN DATAFRAME A PARTIR DEL DICCIONARIO

df = pd.DataFrame(data=data)
df

  Nombre  Edad     Ciudad
0   Juan    22    MAchala
1   Luis    25      Quito
2    Ana    23     Cuenca
3  Maria    30  Guayaquil

In [4]:
#SELECCIONAMOS UNA COLUMNA
nombres = df["Nombre"]
print(nombres, type(nombres))

0     Juan
1     Luis
2      Ana
3    Maria
Name: Nombre, dtype: str <class 'pandas.Series'>

In [5]:
#SELECCIONAMOS MAS DE UNA COLUMNA
df[["Nombre", "Ciudad"]]

  Nombre     Ciudad
0   Juan    MAchala
1   Luis      Quito
2    Ana     Cuenca
3  Maria  Guayaquil

In [6]:
#FILTRAR POR INIDCE
fila = df.loc[2]
print(fila)

Nombre       Ana
Edad          23
Ciudad    Cuenca
Name: 2, dtype: object

In [7]:
#FILTRAR POR CONDICION
df[df["Edad"] > 23]

  Nombre  Edad     Ciudad
1   Luis    25      Quito
3  Maria    30  Guayaquil

In [8]:
#DOBLE CONDICION
#df[(df["Edad"] > 23) & (df["Nombre"].str.startswith("M"))]
filtro = (df["Edad"] > 23) & (df["Nombre"].str.startswith("M"))
df[filtro]

  Nombre  Edad     Ciudad
3  Maria    30  Guayaquil

In [9]:
#filtrar por query
df.query("Edad > 23 and Nombre.str.startswith('M')")

  Nombre  Edad     Ciudad
3  Maria    30  Guayaquil

In [10]:
df[df["Nombre"].isin(["Luis", "Ana", "Carlos"])]

  Nombre  Edad  Ciudad
1   Luis    25   Quito
2    Ana    23  Cuenca

In [11]:
# EXPORTAR UN DATADRAME A CSV
df.to_csv("datos.csv")

In [12]:
#IMPORTAR UN CSV A UN DATAFRAME
#index_col=0 para que la primera columna se convierta en el indice del dataframe
import_df = pd.read_csv("datos.csv", index_col=0)
import_df

  Nombre  Edad     Ciudad
0   Juan    22    MAchala
1   Luis    25      Quito
2    Ana    23     Cuenca
3  Maria    30  Guayaquil

In [13]:
import numpy as np

In [14]:
data = {
    "Nombre" : ["Juan", "Luis", "Ana", "Maria", "Carlos"],
    "Edad" : [22,25,np.nan,30,28],
    "Ciudad" : ["MAchala", "Quito", "Cuenca", None, "Ambato"]
}
df = pd.DataFrame(data)
df

   Nombre  Edad   Ciudad
0    Juan  22.0  MAchala
1    Luis  25.0    Quito
2     Ana   NaN   Cuenca
3   Maria  30.0      NaN
4  Carlos  28.0   Ambato

In [18]:
#RELLENAR LOS VALORES FALTANTES
#Metodo fillna() para rellenar los valores faltantes
#METODO mean DEVUELVE LA MEDIA DE LA COLUMNA
df_fill = df.fillna(
    {
    "Edad" : df["Edad"].mean(),
    "Ciudad" : "Desconocida"
    }
)
df_fill

   Nombre   Edad       Ciudad
0    Juan  22.00      MAchala
1    Luis  25.00        Quito
2     Ana  26.25       Cuenca
3   Maria  30.00  Desconocida
4  Carlos  28.00       Ambato

In [16]:
#ELIMINAMOS LAS FILAS CON VALORES FALTANTES
df_drop = df.dropna()
df_drop

   Nombre  Edad   Ciudad
0    Juan  22.0  MAchala
1    Luis  25.0    Quito
4  Carlos  28.0   Ambato

In [20]:
#REEMPLAZAR VALORES ESPECIFICOS DE UNA COLUMNA
#AQUI SE PUEDEN REEMPLAZAR VARIOS VALORES DE UNA COLUMNA O FILA A LA VEZ
def_reem = df.replace(
    {
        "Ciudad" : {None : "Desconocida"}
    }
)
def_reem

   Nombre  Edad       Ciudad
0    Juan  22.0      MAchala
1    Luis  25.0        Quito
2     Ana   NaN       Cuenca
3   Maria  30.0  Desconocida
4  Carlos  28.0       Ambato

In [21]:
#INTERPOLACION DE VALORES FALTANTES
df_interploado = df.copy()
df_interploado["Edad"] = df_interploado["Edad"].interpolate()
df_interploado

   Nombre  Edad   Ciudad
0    Juan  22.0  MAchala
1    Luis  25.0    Quito
2     Ana  27.5   Cuenca
3   Maria  30.0      NaN
4  Carlos  28.0   Ambato

In [24]:
#TRATAR VALORES DUPLICADOS
data_dupl = {
    "Nombre" : ["Ana", "Juan", "Pedro", "Maria", "Luis", "Ana", "Juan"],
    "Edad" : [22,25,None,23,20,22,25],
    "Ciudad" : ["Barcelona", "Madrid", "Valencia", None, "Bilbao", "Barcelona", "Madrid"]
}
df_dupl = pd.DataFrame(data_dupl)
df_dupl

  Nombre  Edad     Ciudad
0    Ana  22.0  Barcelona
1   Juan  25.0     Madrid
2  Pedro   NaN   Valencia
3  Maria  23.0        NaN
4   Luis  20.0     Bilbao
5    Ana  22.0  Barcelona
6   Juan  25.0     Madrid

In [26]:
#ELIMINAR FILAS DUPLICADAS, TIENEN QUE SER EXACTAMENTE IGUALES PARA SER CONSIDERADAS DUPLICADAS 
df_sin_duplicados = df_dupl.drop_duplicates()
df_sin_duplicados

  Nombre  Edad     Ciudad
0    Ana  22.0  Barcelona
1   Juan  25.0     Madrid
2  Pedro   NaN   Valencia
3  Maria  23.0        NaN
4   Luis  20.0     Bilbao

In [ ]:
#PARA REENOMBRAR LAS COLUMNAS
df_renombrado = df.rename(columns={"Nombre":"Name", "Edad":"Age", "Ciudad":"City"})
df_renombrado

     Name   Age     City
0    Juan  22.0  MAchala
1    Luis  25.0    Quito
2     Ana   NaN   Cuenca
3   Maria  30.0      NaN
4  Carlos  28.0   Ambato

In [29]:
#ORDENAR POR UNA COLUMNA
columnas_ordenadas = ["Ciudad", "Edad", "Nombre"]
df_ordenado = df[columnas_ordenadas]
df_ordenado

    Ciudad  Edad  Nombre
0  MAchala  22.0    Juan
1    Quito  25.0    Luis
2   Cuenca   NaN     Ana
3      NaN  30.0   Maria
4   Ambato  28.0  Carlos

In [30]:
#TRANSFORMACION DE DATOS
def cuadrado(x):
  return x**2

#SE AGREGA UNA NUEVA COLUMNA CON ESTA FUNCION 
df["Edad_Cuadrado"] = df["Edad"].apply(cuadrado)
df

   Nombre  Edad   Ciudad  Edad_Cuadrado
0    Juan  22.0  MAchala          484.0
1    Luis  25.0    Quito          625.0
2     Ana   NaN   Cuenca            NaN
3   Maria  30.0      NaN          900.0
4  Carlos  28.0   Ambato          784.0