In [2]:
import pandas as pd

In [3]:
#DICCIONARIO
data = {
    "Nombre" : ["Juan", "Luis", "Ana", "Maria"],
    "Edad" : [22,25,23,30],
    "Ciudad" : ["MAchala", "Quito", "Cuenca", "Guayaquil"]
}

data, type(data)

({'Nombre': ['Juan', 'Luis', 'Ana', 'Maria'],
  'Edad': [22, 25, 23, 30],
  'Ciudad': ['MAchala', 'Quito', 'Cuenca', 'Guayaquil']},
 dict)

In [4]:
#GENERAMOS UN DATAFRAME A PARTIR DEL DICCIONARIO

df = pd.DataFrame(data=data)
df

  Nombre  Edad     Ciudad
0   Juan    22    MAchala
1   Luis    25      Quito
2    Ana    23     Cuenca
3  Maria    30  Guayaquil

In [5]:
#SELECCIONAMOS UNA COLUMNA
nombres = df["Nombre"]
print(nombres, type(nombres))

0     Juan
1     Luis
2      Ana
3    Maria
Name: Nombre, dtype: str <class 'pandas.Series'>

In [6]:
#SELECCIONAMOS MAS DE UNA COLUMNA
df[["Nombre", "Ciudad"]]

  Nombre     Ciudad
0   Juan    MAchala
1   Luis      Quito
2    Ana     Cuenca
3  Maria  Guayaquil

In [7]:
#FILTRAR POR INIDCE
fila = df.loc[2]
print(fila)

Nombre       Ana
Edad          23
Ciudad    Cuenca
Name: 2, dtype: object

In [8]:
#FILTRAR POR CONDICION
df[df["Edad"] > 23]

  Nombre  Edad     Ciudad
1   Luis    25      Quito
3  Maria    30  Guayaquil

In [9]:
#DOBLE CONDICION
#df[(df["Edad"] > 23) & (df["Nombre"].str.startswith("M"))]
filtro = (df["Edad"] > 23) & (df["Nombre"].str.startswith("M"))
df[filtro]

  Nombre  Edad     Ciudad
3  Maria    30  Guayaquil

In [10]:
#filtrar por query
df.query("Edad > 23 and Nombre.str.startswith('M')")

  Nombre  Edad     Ciudad
3  Maria    30  Guayaquil

In [11]:
df[df["Nombre"].isin(["Luis", "Ana", "Carlos"])]

  Nombre  Edad  Ciudad
1   Luis    25   Quito
2    Ana    23  Cuenca

In [12]:
# EXPORTAR UN DATADRAME A CSV
df.to_csv("datos.csv")

In [13]:
#IMPORTAR UN CSV A UN DATAFRAME
#index_col=0 para que la primera columna se convierta en el indice del dataframe
import_df = pd.read_csv("datos.csv", index_col=0)
import_df

  Nombre  Edad     Ciudad
0   Juan    22    MAchala
1   Luis    25      Quito
2    Ana    23     Cuenca
3  Maria    30  Guayaquil

In [14]:
import numpy as np

In [15]:
data = {
    "Nombre" : ["Juan", "Luis", "Ana", "Maria", "Carlos"],
    "Edad" : [22,25,np.nan,30,28],
    "Ciudad" : ["MAchala", "Quito", "Cuenca", None, "Ambato"]
}
df = pd.DataFrame(data)
df

   Nombre  Edad   Ciudad
0    Juan  22.0  MAchala
1    Luis  25.0    Quito
2     Ana   NaN   Cuenca
3   Maria  30.0      NaN
4  Carlos  28.0   Ambato

In [16]:
#RELLENAR LOS VALORES FALTANTES
#Metodo fillna() para rellenar los valores faltantes
#METODO mean DEVUELVE LA MEDIA DE LA COLUMNA
df_fill = df.fillna(
    {
    "Edad" : df["Edad"].mean(),
    "Ciudad" : "Desconocida"
    }
)
df_fill

   Nombre   Edad       Ciudad
0    Juan  22.00      MAchala
1    Luis  25.00        Quito
2     Ana  26.25       Cuenca
3   Maria  30.00  Desconocida
4  Carlos  28.00       Ambato

In [17]:
#ELIMINAMOS LAS FILAS CON VALORES FALTANTES
df_drop = df.dropna()
df_drop

   Nombre  Edad   Ciudad
0    Juan  22.0  MAchala
1    Luis  25.0    Quito
4  Carlos  28.0   Ambato

In [18]:
#REEMPLAZAR VALORES ESPECIFICOS DE UNA COLUMNA
#AQUI SE PUEDEN REEMPLAZAR VARIOS VALORES DE UNA COLUMNA O FILA A LA VEZ
def_reem = df.replace(
    {
        "Ciudad" : {None : "Desconocida"}
    }
)
def_reem

   Nombre  Edad       Ciudad
0    Juan  22.0      MAchala
1    Luis  25.0        Quito
2     Ana   NaN       Cuenca
3   Maria  30.0  Desconocida
4  Carlos  28.0       Ambato

In [19]:
#INTERPOLACION DE VALORES FALTANTES
df_interploado = df.copy()
df_interploado["Edad"] = df_interploado["Edad"].interpolate()
df_interploado

   Nombre  Edad   Ciudad
0    Juan  22.0  MAchala
1    Luis  25.0    Quito
2     Ana  27.5   Cuenca
3   Maria  30.0      NaN
4  Carlos  28.0   Ambato

In [20]:
#TRATAR VALORES DUPLICADOS
data_dupl = {
    "Nombre" : ["Ana", "Juan", "Pedro", "Maria", "Luis", "Ana", "Juan"],
    "Edad" : [22,25,None,23,20,22,25],
    "Ciudad" : ["Barcelona", "Madrid", "Valencia", None, "Bilbao", "Barcelona", "Madrid"]
}
df_dupl = pd.DataFrame(data_dupl)
df_dupl

  Nombre  Edad     Ciudad
0    Ana  22.0  Barcelona
1   Juan  25.0     Madrid
2  Pedro   NaN   Valencia
3  Maria  23.0        NaN
4   Luis  20.0     Bilbao
5    Ana  22.0  Barcelona
6   Juan  25.0     Madrid

In [21]:
#ELIMINAR FILAS DUPLICADAS, TIENEN QUE SER EXACTAMENTE IGUALES PARA SER CONSIDERADAS DUPLICADAS 
df_sin_duplicados = df_dupl.drop_duplicates()
df_sin_duplicados

  Nombre  Edad     Ciudad
0    Ana  22.0  Barcelona
1   Juan  25.0     Madrid
2  Pedro   NaN   Valencia
3  Maria  23.0        NaN
4   Luis  20.0     Bilbao

In [22]:
#PARA REENOMBRAR LAS COLUMNAS
df_renombrado = df.rename(columns={"Nombre":"Name", "Edad":"Age", "Ciudad":"City"})
df_renombrado

     Name   Age     City
0    Juan  22.0  MAchala
1    Luis  25.0    Quito
2     Ana   NaN   Cuenca
3   Maria  30.0      NaN
4  Carlos  28.0   Ambato

In [23]:
#ORDENAR POR UNA COLUMNA
columnas_ordenadas = ["Ciudad", "Edad", "Nombre"]
df_ordenado = df[columnas_ordenadas]
df_ordenado

    Ciudad  Edad  Nombre
0  MAchala  22.0    Juan
1    Quito  25.0    Luis
2   Cuenca   NaN     Ana
3      NaN  30.0   Maria
4   Ambato  28.0  Carlos

In [24]:
#TRANSFORMACION DE DATOS
def cuadrado(x):
  return x**2

#SE AGREGA UNA NUEVA COLUMNA CON ESTA FUNCION 
df["Edad_Cuadrado"] = df["Edad"].apply(cuadrado)
df

   Nombre  Edad   Ciudad  Edad_Cuadrado
0    Juan  22.0  MAchala          484.0
1    Luis  25.0    Quito          625.0
2     Ana   NaN   Cuenca            NaN
3   Maria  30.0      NaN          900.0
4  Carlos  28.0   Ambato          784.0

In [27]:
#AGRUPACION DE DATOS
data = {
    "Nombre": ["Juan", "Ana", "Luis", "Laura", "Pedro", "Carla"],
    "Ciudad": ["Madrid", "Barcelona", "Madrid", "Valencia", "Barcelona", "Madrid"],
    "Edad": [25, 33,30,28,45,38],
    "Puntuacion": [80, 90 ,85, 88, 75, 91]
    }
df = pd.DataFrame(data)
df

  Nombre     Ciudad  Edad  Puntuacion
0   Juan     Madrid    25          80
1    Ana  Barcelona    33          90
2   Luis     Madrid    30          85
3  Laura   Valencia    28          88
4  Pedro  Barcelona    45          75
5  Carla     Madrid    38          91

In [28]:
#AGRUPAR DATOS POR CIUDAD
grouped = df.groupby("Ciudad")
print(grouped.groups)

{'Barcelona': [1, 4], 'Madrid': [0, 2, 5], 'Valencia': [3]}

In [29]:
#CACULAR LA SUMA DE LAS EDADES Y PUNTUACIONES POR CIUDAD
agregated_data = grouped.agg(
    {
        "Edad": "mean",
        "Puntuacion": "sum"
    }
)
agregated_data

           Edad  Puntuacion
Ciudad
Barcelona  39.0         165
Madrid     31.0         256
Valencia   28.0          88

In [ ]:
#DEFINIMOS UNA FUNCION DE AGREGACION PERSONALIZADA
#EL RANGO EN ESTE CASO ES AL VARIACION ENTRE LE MAXIMO VALOR Y EL MINIMO
def rango(series):
    return series.max() - series.min()

#APLICAMOS LA FUNCION DE AGREGACION PERSONALIZADA A LA COLUMNA DE EDAD
agregated_data_custom = grouped.agg(
    {  
        "Edad": rango,
        "Puntuacion": rango
    }
    )
print (agregated_data_custom)

           Edad  Puntuacion
Ciudad
Barcelona    12          15
Madrid       13          11
Valencia      0           0

In [32]:
#AGRUPACION DE DATOS
data["Categoria"] = ["A", "B", "A", "B", "A", "B"]
df = pd.DataFrame(data)
df

  Nombre     Ciudad  Edad  Puntuacion Categoria
0   Juan     Madrid    25          80         A
1    Ana  Barcelona    33          90         B
2   Luis     Madrid    30          85         A
3  Laura   Valencia    28          88         B
4  Pedro  Barcelona    45          75         A
5  Carla     Madrid    38          91         B

In [33]:
#AGREGAR UNA NUEVA COLUMNA CON UNA FUNCION LAMBDAAGRUPACION DE DATOS POR CIUDAD Y CATEGORIA
grouped_mult = df.groupby(["Ciudad", "Categoria"])
grouped_mult.groups

{('Barcelona', 'A'): RangeIndex(start=4, stop=5, step=1),
 ('Barcelona', 'B'): RangeIndex(start=1, stop=2, step=1),
 ('Madrid', 'A'): RangeIndex(start=0, stop=4, step=2),
 ('Madrid', 'B'): RangeIndex(start=5, stop=6, step=1),
 ('Valencia', 'B'): RangeIndex(start=3, stop=4, step=1)}

In [34]:
#AGREGADO DE CALCULAR LAS UMA DE EDADES Y PUNTUACIONES POR CIUDAD Y CATEGORIA
agregated_data_multi = grouped_mult.agg(
    {
        "Edad": "sum",
        "Puntuacion": "mean"
    }
)
agregated_data_multi

                     Edad  Puntuacion
Ciudad    Categoria
Barcelona A            45        75.0
          B            33        90.0
Madrid    A            55        82.5
          B            38        91.0
Valencia  B            28        88.0

In [42]:
#AGREGAMOS UNA COLUMAN
data = {
    "Nombre": ["Juan", "Ana", "Luis", "Laura"],
    "Edad" : [25,33,30,28]
}
df = pd.DataFrame(data)
df

  Nombre  Edad
0   Juan    25
1    Ana    33
2   Luis    30
3  Laura    28

In [43]:
#AQUI AGREGAMOS UNA COLUMA SIN MODIFICAR EL DATASET ORIGINAL
df["Ciudad"] = ["Madrid", "Barcelona", "Madrid", "Valencia"]
df

  Nombre  Edad     Ciudad
0   Juan    25     Madrid
1    Ana    33  Barcelona
2   Luis    30     Madrid
3  Laura    28   Valencia

In [44]:
#GENERAMOS UNA NUEVA FILA
new_row= pd.Series({"Nombre": "Pedro", "Edad": 45, "Ciudad": "Bilbao"})

#AGREGAMOS LA FILA
# EL .T ES PARA HACER LA TRANSPUESTA YA QUE ESTE SE CRE ORIGINALMENTE COMO UNA COLUMNA Y NOSOTROS ESTAMOS AGREGANDO UNA FILA
#ignore_index=True PARA QUE SE REASIGNE EL INDICE DEL DATAFRAME DESPUES DE AGREGAR LA FILA
df = pd.concat([df, new_row.to_frame().T], ignore_index=True)
df

  Nombre Edad     Ciudad
0   Juan   25     Madrid
1    Ana   33  Barcelona
2   Luis   30     Madrid
3  Laura   28   Valencia
4  Pedro   45     Bilbao

In [48]:
#COMBINAR DATA FRAMES
#AGREGAR FILAS 
data = {
    "Nombre": ["Juan", "Ana", "Luis", "Laura"],
    "Edad" : [25,33,30,28],
    "Ciudad" : ["Madrid", "Barcelona", "Madrid", "Valencia"]
}
df = pd.DataFrame(data)

data2 = {
    "Nombre" : ["Carla", "Irene"],
    "Edad" : [38, 27],
    "Ciudad" : ["Bilbao", "Madrid"]
}
df2 = pd.DataFrame(data2)

In [49]:
df

  Nombre  Edad     Ciudad
0   Juan    25     Madrid
1    Ana    33  Barcelona
2   Luis    30     Madrid
3  Laura    28   Valencia

In [47]:
df2

  Nombre  Edad  Ciudad
0  Carla    38  Bilbao
1  Irene    27  Madrid

In [51]:
df_combined =pd.concat([df,df2], ignore_index=True)
df_combined

  Nombre  Edad     Ciudad
0   Juan    25     Madrid
1    Ana    33  Barcelona
2   Luis    30     Madrid
3  Laura    28   Valencia
4  Carla    38     Bilbao
5  Irene    27     Madrid